/* eslint-disable react/prop-types */
// import "./ArtisanSettings.scss";
import personIcon from "../../assets/icons/person-1-icon.svg";
import personAddIcon from "../../assets/icons/person-add-icon.svg";
import securityIcon from "../../assets/icons/security-icon.svg";
import activityIcon from "../../assets/icons/activity-history-icon.svg";
import backButton from "../../assets/icons/prev-arrow.svg";
import rightArrow from "../../assets/icons/arrow-down.svg";
import qrCodeIcon from "../../assets/icons/ri-qr-code-line.svg";
import referralImage from "../../assets/images/referral.png";
import { Link, Route, Routes } from "react-router-dom";
import { artisanProfileInfo, transactionData2 } from "../../data/Datasets";
import TextBoxCard from "../components/TextBoxCard";
import TransactionItem from "../components/TransactionItem";

const settingsContent = [
  {
    icon: personIcon,
    title: "Personal Information",
    link: "./personalInformation",
  },
  {
    icon: personAddIcon,
    title: "Password & Security",
    link: "./passwordSecurity",
  },
  {
    icon: securityIcon,
    title: "Send Invite",
    link: "./sendInvite",
  },
  {
    icon: activityIcon,
    title: "Activity",
    link: "./activity",
  },
];

const ArtisanSettings = () => {
  return (
    <div className=" flex flex-auto w-full ">
      <Routes>
        <Route path="/" exact Component={SettingsHomes} />
        <Route
          path="/personalInformation"
          exact
          Component={PersonalInformationPage}
        />
        <Route
          path="/passwordSecurity"
          exact
          Component={PasswordSecurityPage}
        />
        <Route path="/sendInvite" exact Component={SendInvite} />
        <Route path="/activity" exact Component={Activity} />
      </Routes>
    </div>
  );
};

export default ArtisanSettings;

const SettingsCard = (props) => (
  <Link to={props.link} className="  ">
    <div className="flex flex-col items-center justify-center gap-[10px] rounded-[10px] hover:bg-pale-blue-grey bg-[#fff] shadow-3xl px-[15px] pt-[25px] h-[150px] w-[160px] md:w-[180px] ">
      <img src={props.icon} alt="settings icon" className=" w-[45px] " />
      <div className=" md:text-[14px] text-[12px] ">{props.title}</div>
    </div>
  </Link>
);

const SettingsHomes = () => (
  <div className="settings-home artisan-settings-container">
    <h1 className="text-[24px] text-main-color font-[600] mb-[20px]">
      Settings
    </h1>
    <div className=" flex flex-wrap gap-[20px] justify-center ">
      {settingsContent.map((content, index) => (
        <SettingsCard
          key={index}
          icon={content.icon}
          title={content.title}
          link={content.link}
        />
      ))}
    </div>
  </div>
);

const SettingsChildPage = (props) => (
  <div className=" flex flex-col w-full gap-[20px] ">
    <div className=" flex items-center gap-[10px] ">
      <Link to="../">
        <img className=" w-[40px] " src={backButton} alt="back button" />
      </Link>
      <h2 className=" text-[24px] text-main-color font-[600] ">Settings</h2>
      <img className="right-arrow" src={rightArrow} alt="back button" />
      <p>{props.childLink}</p>
    </div>
    <div className="">{props.childContent}</div>
  </div>
);

const PasswordSecurityPage = () => (
  <SettingsChildPage
    childLink="Password & Security"
    childContent={
      <div className="flex flex-wrap gap-[20px] flex-auto ">
        <div className=" flex flex-col gap-[20px] lg:max-w-[450px] ">
          <h2 className="text-[20px] font-[600] text-primary-text-color-black">
            Password & Security
          </h2>
          <div className=" w-[450px] flex flex-col gap-[10px] ">
            <TextBoxCard title="Password" content="**********" />
            <TextBoxCard title="Security code" content="2345" />

            <button className=" primary-button-blue h-[50px] w-auto ">
              Change Password
            </button>
          </div>
        </div>
        <div className=" flex flex-col gap-[20px] lg:max-w-[450px] ">
          <h2 className="text-[20px] font-[600] text-primary-text-color-black">
            Two Factor Authentication
          </h2>
          <div className=" flex flex-col gap-[20px] ">
            <h3 className=" text-[16px] font-[600] ">
              Enable Two-Factor Authentication
            </h3>
            <p>
              1. To enable 2FA, you need to install an authenticator app like
              Authy, or Google Authenticator.
            </p>
            <p>
              2. Scan the QR code shown below with your authenticator app. If
              you can’t scan this barcode, enter the text code (Nue99PSH) on the
              authenticator app.
            </p>
            <p>3. Enter the OTP generated by the app and click enable</p>
            <img
              src={qrCodeIcon}
              alt=" qr code image "
              className=" w-[100px] "
            />
          </div>
          <button className=" primary-button-blue h-[50px] w-auto ">
            Authenticate
          </button>
        </div>
      </div>
    }
  />
);

const PersonalInformationPage = () => (
  <SettingsChildPage
    childLink="Personal Information"
    childContent={
      <div className=" flex flex-wrap flex-auto gap-[20px] ">
        <div className="relative flex-col flex w-[100%] rounded-[10px] md:w-[250px] overflow-hidden object-fill ">
          <img
            src={artisanProfileInfo[0].picture}
            alt="profile image"
            className="profile-image  "
          />
          <p className=" absolute text-primary-text-color-white bottom-[0px] bg-[#0a0a0c7e] p-[5px] leading-5 ">
            You can only change your profile picture once in a year(or 6 months)
          </p>
        </div>
        <div className="flex flex-col gap-[20px] w-full md:w-[350px] ">
          <h2 className="text-[20px] font-[600] text-primary-text-color-black">
            Personal Information
          </h2>
          <div className=" flex flex-col gap-[10px]  ">
            <TextBoxCard
              title="First name"
              content={artisanProfileInfo[0].firstName}
            />
            <TextBoxCard
              title="Last name"
              content={artisanProfileInfo[0].lastName}
            />

            <TextBoxCard
              title="Other name"
              content={artisanProfileInfo[0].otherName}
            />
            <TextBoxCard
              title="Country"
              content={artisanProfileInfo[0].country}
            />
          </div>
        </div>
      </div>
    }
  />
);

const Activity = () => (
  <SettingsChildPage
    childLink="Activity"
    childContent={
      <div className=" flex flex-col flex-auto gap-[20px] ">
        <h2 className=" text-[20px] font-[600] text-primary-text-color-black  ">
          Activity Log
        </h2>
        <table className="recent-transactions-collection flex-auto flex-col gap-[12px] ">
          <thead className="transaction-item flex-auto flex-col gap-[12px] ">
            <tr className="flex px-[10px] bg-[#B4CCFC1A] items-center md:text-[16px] text-[12px] justify-between">
              <th className="transaction-date md:w-[80px] w-[80px] h-[40px] flex items-center ">
                Date
              </th>
              <th className="transaction-activity md:w-[150px] w-[120px] h-[40px] flex items-center ">
                Activity
              </th>
              <th className="transaction-description text-clip md:w-[150px] w-[50px] h-[40px] md:flex items-center hidden ">
                Description
              </th>
              <th className="transaction-description md:w-[150px] w-[50px] h-[40px] flex justify-center items-center md:hidden ">
                ...
              </th>
              <th className="transaction-status md:w-[150px] w-[100px] h-[40px] flex items-center justify-end ">
                Status
              </th>
            </tr>
          </thead>
          <tbody className=" flex flex-col gap-[10px] pt-[10px] ">
            {transactionData2.map((content, index) => (
              <TransactionItem
                key={index}
                date={content.date}
                activity={content.activity}
                description={content.description}
                status={content.status}
              />
            ))}
          </tbody>
        </table>
      </div>
    }
  />
);

const SendInvite = () => (
  <SettingsChildPage
    childLink="Send Invite"
    childContent={
      <div className=" flex flex-col gap-[10px] justify-center items-center px-[20px] ">
        <h2 className=" text-[20px] font-[600] ">Send Invite</h2>
        <img src={referralImage} alt="referral image" />
        <div className=" flex flex-col gap-[10px] justify-center items-center ">
          <h2 className=" text-[16px] text-main-color font-[600]  ">
            Copy Referral Link:
          </h2>
          <p className="referral-link">
            https://servvmarketplace.com/invite/a98fjjs9292dfx
          </p>
        </div>
      </div>
    }
  />
);
